---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-basics"
      include_role:
        name: "ansible-role-basics"
        apply:
          become: true
      vars:
        basics_users:
          - vagrant
        basics_bashrc: true
        basics_desktop:
          enabled: true
          autologin_user: vagrant
  
