---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible-role-basics"
        include_role:
          name: "ansible-role-basics"
          apply:
            become: true
        vars:
          basics_users:
            enabled: true
            sudo: true
            users:
              - vagrant
              - gepardec
          basics_bashrc: 
            enabled: true
            global: false
...