---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-basics"
      include_role:
        name: "ansible-role-basics"
        apply:
          become: true
      vars:
        basics_users:
          - gepardec
        basics_bashrc: true
        basics_desktop:
          enabled: true
          autologin_user: gepardec
          remote_desktop:
            enabled: true
            version: "6.9.2_1"
...  