---
  - name: Install epel-release
    yum:
      name: epel-release
      state: present

  - name: Install desktop
    yum:
      name: "{{ basics_desktop_packages }}"
      state: present
    register: desktop
    changed_when: desktop.rc == 0
    failed_when: desktop.rc != 1 and desktop.rc != 0

  - name: Get default runlevel
    command: systemctl get-default
    register: runlevel
    changed_when: false

  - name: Set graphical runlevel
    command: systemctl set-default graphical.target
    when: runlevel.stdout != "graphical.target"

  - name: Is graphical currently active
    command: systemctl is-active graphical.target
    register: graphical
    failed_when: graphical.rc != 3 and graphical.rc != 0
    changed_when: false

  - name: Switch to graphical runlevel
    command: systemctl isolate graphical.target
    when: graphical.stdout != "active"

  - name: Enable autologin
    template:
      src: gdm.custom.conf.j2
      dest: /etc/gdm/custom.conf
      mode: '0544'
    notify: "restart gdm"
    when:
      - basics_desktop.autologin_user is defined

  - name: Create backgrounds folder
    file:
      path: /usr/share/backgrounds/images
      state: directory
      mode: '0755'

  - name: Set background
    copy:
      src: wallpaper.jpg
      dest: /usr/share/backgrounds/images/default.png
      mode: '0644'
    notify: "restart gdm"

  - name: get latest remote desktop download page
    uri:
      url: "https://www.nomachine.com/download/download&id=2"
      return_content: yes
      dest: /tmp/bashrc_remote_desktop_download_page
    changed_when: False
    register: bashrc_remote_desktop_download_page
    notify: cleanup

  - name: get latest remote desktop version
    shell: set -o pipefail &&
      cat /tmp/bashrc_remote_desktop_download_page |
      grep ">Download</a></div></div>" |
      sed -E 's/.*([[:digit:]]+(\.[[:digit:]]+(\.[[:digit:]]+(_[[:digit:]]+)+)+)+)_amd64\.deb.*/\1/'
    changed_when: False
    register: bashrc_remote_desktop_full_version

  - name: get version path for remote desktop
    shell: set -o pipefail &&
      echo "{{ bashrc_remote_desktop_full_version.stdout }}" |
      sed -E "s/^([[:digit:]]+(\.[[:digit:]]+)).*/\1/"
    changed_when: False
    register: bashrc_remote_desktop_version_path

  - name: Install remote desktop
    yum:
      name: "https://download.nomachine.com/packages/{{ bashrc_remote_desktop_version_path.stdout }}
        -PRODUCTION/Linux/nomachine-enterprise-desktop_{{ bashrc_remote_desktop_full_version.stdout }}_x86_64.rpm"
      state: present
    when:
      - basics_desktop.remote_desktop is defined
      - basics_desktop.remote_desktop.enabled

  - name: Use default panel
    copy:
      src: /etc/xdg/xfce4/panel/default.xml
      dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
      remote_src: yes
      mode: '0644'
    notify: "restart gdm"
...