---
dependency:
  name: gilt
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance-1
    image: centos:7
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
