---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible-role-basics"
        include_role:
          name: "ansible-role-basics"
          apply:
            become: true
        vars:
          basics_timezone: 
            enabled: true
            value: Europe/Vienna
...