---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible-role-basics"
        include_role:
          name: "ansible-role-basics"
          apply:
            become: true
        vars:
          basics_bashrc:
            enabled: false
          basics_keymap:
            enabled: true
            value: de
          basics_desktop:
            enabled: true
            autologin_user: vagrant
            remote_desktop:
              enabled: false
...