---
  - name: Verify
    hosts: all
    become: true
    tasks:
      - name: Check gdm is running
        service:
          name: gdm
          state: started
          enabled: true
        check_mode: true
        register: gdm
        failed_when: gdm.changed

      - name: Check remotedesktop is running
        service:
          name: nomachine
          state: started
          enabled: true
        check_mode: true
        register: nomachine
        failed_when: nomachine.changed
...