---
  - name: Converge
    hosts: all
    tasks:
      - name: "Include ansible-role-basics"
        include_role:
          name: "ansible-role-basics"
          apply:
            become: true
        vars:
          basics_bashrc:
            enabled: false
          basics_packages:
            enabled: false
            epel: true
            packages: []
...