---
  dependency:
    name: galaxy
  driver:
    name: vagrant
    provider:
      name: libvirt
  platforms:
    - name: ansible-role-basics
      box: centos/7
      cpus: 1
      memory: 2048
  provisioner:
    name: ansible
    playbooks:
      converge: ../resources/bashrc-global/converge.yml
      verify: ../resources/bashrc-global/verify.yml
  verifier:
    name: ansible
  lint: |
    set -e
    ansible-lint .
...